from pathlib import Path
import sys


REPO_ROOT = Path(workflow.basedir).resolve().parent


configfile: str(REPO_ROOT / "config.yml")


if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from workflow.lib.common import get_layout_paths, normalize_workflow_config, resolve_llvm_version


WORKFLOW_CONFIG = normalize_workflow_config(config)
BASE_DIR = Path(WORKFLOW_CONFIG["project"]["base_dir"]).expanduser().resolve()
RUN_LABEL = str(WORKFLOW_CONFIG["runs"]["run_label"])

LLVM_TAG = str(WORKFLOW_CONFIG["llvm"]["tags"][0])
LLVM_VERSION = resolve_llvm_version(LLVM_TAG)

OFFICIAL_TAG = str(WORKFLOW_CONFIG["test_suite"]["official"]["tags"][0])
RAJA_TAG = str(WORKFLOW_CONFIG["test_suite"]["raja"]["tags"][0])

LAYOUT = get_layout_paths(BASE_DIR, LLVM_TAG, OFFICIAL_TAG, RAJA_TAG, LLVM_VERSION, RUN_LABEL)


rule all:
    input:
        str(LAYOUT["reports_run_dir"] / "benchmark_report.html"),


rule checkout_llvm:
    output:
        source_dir=directory(str(LAYOUT["llvm_source"])),
        stamp=str(LAYOUT["llvm_source"] / ".checkout_complete"),
    log:
        str(LAYOUT["logs_run_dir"] / "checkout_llvm.log"),
    params:
        repo_url=WORKFLOW_CONFIG["llvm"]["repo_url"],
        tag_or_branch=LLVM_TAG,
    script:
        "scripts/checkout_repo.py"


rule checkout_official:
    output:
        source_dir=directory(str(LAYOUT["official_source"])),
        stamp=str(LAYOUT["official_source"] / ".checkout_complete"),
    log:
        str(LAYOUT["logs_run_dir"] / "checkout_official.log"),
    params:
        repo_url=WORKFLOW_CONFIG["test_suite"]["official"]["repo_url"],
        tag_or_branch=OFFICIAL_TAG,
        recursive=False,
    script:
        "scripts/checkout_repo.py"


rule checkout_raja:
    output:
        source_dir=directory(str(LAYOUT["raja_source"])),
        stamp=str(LAYOUT["raja_source"] / ".checkout_complete"),
    log:
        str(LAYOUT["logs_run_dir"] / "checkout_raja.log"),
    params:
        repo_url=WORKFLOW_CONFIG["test_suite"]["raja"]["repo_url"],
        tag_or_branch=RAJA_TAG,
        recursive=True,
    script:
        "scripts/checkout_repo.py"


rule build_llvm:
    input:
        checkout_stamp=str(LAYOUT["llvm_source"] / ".checkout_complete"),
    output:
        clangxx=str(LAYOUT["llvm_install"] / "bin" / "clang++"),
        stamp=str(LAYOUT["llvm_build"] / ".build_complete"),
    log:
        str(LAYOUT["logs_run_dir"] / "build_llvm.log"),
    params:
        source_dir=str(LAYOUT["llvm_source"]),
        build_dir=str(LAYOUT["llvm_build"]),
        install_dir=str(LAYOUT["llvm_install"]),
        host_c_compiler=WORKFLOW_CONFIG["llvm"]["build"]["c_compiler"],
        host_cxx_compiler=WORKFLOW_CONFIG["llvm"]["build"]["cxx_compiler"],
        ninja_jobs=WORKFLOW_CONFIG["llvm"]["build"]["ninja_jobs"],
    script:
        "scripts/build_llvm.py"


rule build_official:
    input:
        checkout_stamp=str(LAYOUT["official_source"] / ".checkout_complete"),
        llvm_clangxx=str(LAYOUT["llvm_install"] / "bin" / "clang++"),
        llvm_stamp=str(LAYOUT["llvm_build"] / ".build_complete"),
    output:
        cache=str(LAYOUT["official_build"] / "CMakeCache.txt"),
        stamp=str(LAYOUT["official_build"] / ".build_complete"),
    log:
        str(LAYOUT["logs_run_dir"] / "build_official.log"),
    params:
        source_dir=str(LAYOUT["official_source"]),
        build_dir=str(LAYOUT["official_build"]),
        llvm_install_dir=str(LAYOUT["llvm_install"]),
        cxx_standard=WORKFLOW_CONFIG["test_suite"]["official"]["cxx_standard"],
        ninja_jobs=WORKFLOW_CONFIG["llvm"]["build"]["ninja_jobs"],
    script:
        "scripts/build_official.py"


rule build_raja:
    input:
        checkout_stamp=str(LAYOUT["raja_source"] / ".checkout_complete"),
        llvm_clangxx=str(LAYOUT["llvm_install"] / "bin" / "clang++"),
        llvm_stamp=str(LAYOUT["llvm_build"] / ".build_complete"),
    output:
        exe=str(LAYOUT["raja_build"] / "bin" / "raja-perf.exe"),
        stamp=str(LAYOUT["raja_build"] / ".build_complete"),
    log:
        str(LAYOUT["logs_run_dir"] / "build_raja.log"),
    params:
        source_dir=str(LAYOUT["raja_source"]),
        build_dir=str(LAYOUT["raja_build"]),
        llvm_install_dir=str(LAYOUT["llvm_install"]),
        cxx_standard=WORKFLOW_CONFIG["test_suite"]["raja"]["cxx_standard"],
        ninja_jobs=WORKFLOW_CONFIG["llvm"]["build"]["ninja_jobs"],
    script:
        "scripts/build_raja.py"


rule run_official:
    input:
        build_stamp=str(LAYOUT["official_build"] / ".build_complete"),
        llvm_clangxx=str(LAYOUT["llvm_install"] / "bin" / "clang++"),
    output:
        results=str(LAYOUT["official_result"] / "baseline_results.json"),
        stamp=str(LAYOUT["official_result"] / ".run_complete"),
    log:
        str(LAYOUT["logs_run_dir"] / "run_official.log"),
    params:
        build_dir=str(LAYOUT["official_build"]),
    script:
        "scripts/run_official.py"


rule run_raja:
    input:
        build_stamp=str(LAYOUT["raja_build"] / ".build_complete"),
        exe=str(LAYOUT["raja_build"] / "bin" / "raja-perf.exe"),
    output:
        results=str(LAYOUT["raja_result"] / "RAJAPerf-kernel-run-data.csv"),
        stamp=str(LAYOUT["raja_result"] / ".run_complete"),
    log:
        str(LAYOUT["logs_run_dir"] / "run_raja.log"),
    params:
        exe=str(LAYOUT["raja_build"] / "bin" / "raja-perf.exe"),
        result_dir=str(LAYOUT["raja_result"]),
    script:
        "scripts/run_raja.py"


rule parse_results:
    input:
        official_results=str(LAYOUT["official_result"] / "baseline_results.json"),
        official_stamp=str(LAYOUT["official_result"] / ".run_complete"),
        raja_results=str(LAYOUT["raja_result"] / "RAJAPerf-kernel-run-data.csv"),
        raja_stamp=str(LAYOUT["raja_result"] / ".run_complete"),
    output:
        parsed_csv=str(LAYOUT["parsed_run_dir"] / "benchmark_records.csv"),
    log:
        str(LAYOUT["logs_run_dir"] / "parse_results.log"),
    params:
        input_dir=str(LAYOUT["results_root"]),
        run_label=RUN_LABEL,
    shell:
        ".venv/bin/python workflow/scripts/parse_results_cli.py --input-dir {params.input_dir} --run-label {params.run_label} --output-file {output.parsed_csv} > {log} 2>&1"


rule aggregate_results:
    input:
        parsed_csv=str(LAYOUT["parsed_run_dir"] / "benchmark_records.csv"),
    output:
        aggregated_csv=str(LAYOUT["parsed_run_dir"] / "benchmark_records_aggregated.csv"),
    log:
        str(LAYOUT["logs_run_dir"] / "aggregate_results.log"),
    shell:
        ".venv/bin/python workflow/scripts/aggregate_results_cli.py --input-file {input.parsed_csv} --output-file {output.aggregated_csv} > {log} 2>&1"


rule generate_report:
    input:
        aggregated_csv=str(LAYOUT["parsed_run_dir"] / "benchmark_records_aggregated.csv"),
    output:
        html=str(LAYOUT["reports_run_dir"] / "benchmark_report.html"),
    log:
        str(LAYOUT["logs_run_dir"] / "generate_report.log"),
    shell:
        ".venv/bin/python workflow/scripts/generate_report_cli.py --input-file {input.aggregated_csv} --output-html {output.html} > {log} 2>&1"
