project:
  base_dir: "~/msc/auto"
  # default_platform: "eidf-vm"

build:
  ninja_jobs:
    - "-j"
    - "6"

runs:
#   labels:
#     - "baseline"
  repeat_count: 1

# experiments:
#   - name: "llvm-21-baseline"
#     llvm_tag: "llvmorg-21.1.0"
#     official_tag: "llvmorg-21.1.0"
#     raja_tag: "v2025.12.0"
#     run_label: "baseline"
#   - name: "llvm-21-repeat"
#     llvm_tag: "llvmorg-21.1.0"
#     official_tag: "llvmorg-21.1.0"
#     raja_tag: "v2025.12.0"
#     run_label: "baseline"
#     repeat_count: 3

llvm:
  repo_url: "https://github.com/llvm/llvm-project.git"
  tags:
    - "llvmorg-21.1.0"
  build:
    c_compiler: "gcc"
    cxx_compiler: "g++"

test_suite:
  official:
    repo_url: "https://github.com/llvm/llvm-test-suite.git"
    tags:
      - "llvmorg-21.1.0"
    cxx_standard: "17"

  raja:
    repo_url: "https://github.com/LLNL/RAJAPerf.git"
    tags:
      - "v2025.12.0"
    cxx_standard: "17"
